### ISSUE TITLE
Error while updating the Application

### ISSUE THREAD

**Issue by tbitowt** [ProgTrade/nUpdate#24]
Hello,

I have problem with updating application. After I ran `manager.InstallPackage();` installation progress is shown, but in a while I got error
![image](https://cloud.githubusercontent.com/assets/6546880/12240984/bafcefe6-b890-11e5-9bb1-01afa0a0c87b.png)

I have tried everything to get rid of this error, nothing helps.

Could you please guilde me what am I doing wrong?

PS. This is how I'm doing it right now (not working OFC)

```
Task.Factory.StartNew(async () =>
        {
            await Task.Delay(TimeSpan.FromSeconds(10));
            UpdateManager manager = new UpdateManager(...)
            var forUpdates = manager.SearchForUpdates();
            if (forUpdates)
            {
                manager.DownloadPackages();
                manager.CloseHostApplication = true;
                manager.InstallPackage();
            }
        });
```

**Comment by ProgTrade** [comment]
Hi,

sorry for my late response, I didn't get any notification from GitHub.
Anyway, first of all, you can delete the line `manager.CloseHostApplication = true;` as this value is the default.
You're closing the application, so that shouldn't be the problem. There must be any other program that currently uses the file and thus, it cannot be overwritten.

Have you tried closing all programs (also Visual Studio, if you're testing that one)?

**Comment by ProgTrade** [comment]
@tbitowt Were you able to fix the problem?

**Comment by ProgTrade** [comment]
There were no further responses or questions, so the problem could apparently be fixed.
