### ISSUE TITLE
Not friendly for old .NET and VS version.

### ISSUE THREAD

**Issue by SSSANTON** [ProgTrade/nUpdate#27]
The lastest nUpdate build in VS2015, some of the source code used the new C# feature, like "$",“??”,"?."
But many C# projects are based on .NET4.0.....

**Comment by AliveDevil** [comment]
That's bad because?
If it's in DLLs SourceCode who cares? If you want to develop for nUpdate: Sure, update to latest version. Otherwise it does not count because null-conditional and string interpolation are just syntactic sugar (?? (null-coalescing) exists since at least C#3) and do not require a newer version of .NET or VS.
-> Fun fact: nUpdate is based on .NET 4.0 as well.

**Comment by ProgTrade** [comment]
I really agree with @AliveDevil here. Syntactic features in C#6 do not concern the DLL that is being compiled. So, there shouldn't be any problem due to the integration of nUpdate into your project.

As said above, if you want to develop something on-top of nUpdate, you must upgrade your version of VS to the newest one. C#6 provides so many useful features that I won't renounce as they facilitate the development.

Also, nUpdate is based in .NET 4.0, so I don't quite understand your argumentation. Did you take a look at the specifications? And I will surely not downgrade the framework version any further as every PC using Windows Vista (minimum) should have .NET 4, or even .NET 4.5, installed. It could even run on XP but that point is redundant as I'm not supporting and over 10 year old operating system any longer.
