### ISSUE TITLE
How to getting start?

### ISSUE THREAD

**Issue by a359807859** [ProgTrade/nUpdate#40]
hello,i want to use this,but i don't know how to getting start.can you write wiki to teach me?

**Comment by ProgTrade** [comment]
Hi,

I will try to add some pages to the wiki throughout the next days.

In general you need a project in nUpdate.Administration that will be linked with your application, that should be updated, over the update configuration.
Then you can open this project and manage the packages. You will also find a section containing a button which allows you to copy the source code for your application in order to allow it to update.

Best,
Dominic

**Comment by a359807859** [comment]
Thank you, I have successfully deployed to the website and updated in the software. This is a great software!

**Comment by ProgTrade** [comment]
Alright, nice to hear that. Thank you. :)
