### ISSUE TITLE
Add package files only when they're already existing

### ISSUE THREAD

**Issue by vector-man** [ProgTrade/nUpdate#41]
Hi. I have a question about nUpdate. Does it support updates if a certain extension folder is present?

For example: I have an application that supports extensions (like Google Chrome). If an extension were installed in the following directory: myapp/extensions/coolExtension, nUpdate will continually update this extension to the latest version, when available. However, if the extension was not installed (is not present in my application's extension folder) nUpdate will not show/allow updates for this extension (i.e. it will ultimately ignore updates for that particular extension and simply provide updates for other installed extensions or the application itself).

Is this possible?

**Comment by ProgTrade** [comment]
Hi,

I understand what you mean. You do not want nUpdate to extract any files into that extension folder, if it has not been installed. But, at the same time, you want to add these updated files to the package in order to offer them to users who have this extension installed on their computer.
In short: You want to set conditions for specifying, if the files you added should be extracted.
This cannot be done directly using the corresponding "Replace files/folders" operation as this one does either add them, if they do not yet exist, or replace them, if they do.

What you can do is the following: You may want to add the files for this extension inside of the AppData or the Temp folder. Then you may check the existance of your extension and copy them in your application instead of letting nUpdate do that.
Otherwise, you can add a C#-script to your package and do it there. This would mean that nUpdate does it for you and this is not part of your application.

Best,
Dominic

**Comment by ProgTrade** [comment]
@vector-man Did this help you or do you still have problems according to this issue?

**Comment by vector-man** [comment]
Hi,

Thanks for the response. Yeah, that should work. I've decided to rethink the updating process too. 

Thanks,

Mike
