### ISSUE TITLE
Working on different Computers 

### ISSUE THREAD

**Issue by KillTrot** [ProgTrade/nUpdate#44]
Hello,

I'm currently working on the same project from different computers with Git.
As the whole project, I also copy the update.nupdproj with Git, and this seems to be a problem.
A path string is stored inside the update.nupdproj, and because i'm sometimes on another computer, it cannot find this local path.
It's not a big problem, i just edited the update.nupdproj myself, so it fits the path, but I think you could improve there a little bit.

--------------------------------------------

Nochmals in Deutsch, da mein Englisch nicht das Beste ist.

Ich arbeite momentan an einem Projekt mit mehreren Arbeitsplätzen, wobei mit Git gearbeitet wird, um immer die aktuellste Version auf jedem Rechner zu haben (des Sources).
Nun hatte ich damals auf Rechner 1 das nUpdate Projekt erstellt und die update.nupdproj Datei einfach auch mit Git synchronisiert, damit ich Updates auch vom zweiten Rechner aus hochladen kann.
Leider scheint dies nicht so einfach zu gehen.
Ich habe herausgefunden, dass in der update.nupdproj ein lokaler Pfad als String gespeichert ist (der Datei-eigene Pfad) der natürlich auf einem anderen Rechner nicht mehr unbedingt stimmt.
Ich konnte das Problem umgehen, in dem ich die Datei mit einem Texteditor geöffnet und von Hand den Pfad geändert habe, so dass es danach stimmte.
Dennoch denke ich, dass man hier eventuell etwas ändern könnte, auch wenn es nicht direkt notwendig ist.

Greetings KillTrot

**Comment by KillTrot** [comment]
Nevermind...
You already implemented an import function...

Keeping my eyes open,
KillTrot

**Comment by ProgTrade** [comment]
Hi KillTrot,

yes, that's indeed a problem in version 3.x. I need to admit that the project management is kind of messed up there (also due to some other facts). This will be improved/changed in version 4.x which is currently under development (see the `develop`-branch for more).
What you can do for now (and what you just found :D) is: Open nUpdate Administration, choose "Import/Export project", choose the "Export"-option and then follow the steps. This will create a .ZIP-file which you can import using nUpdate Administration on the other computer. Then everything should be fixed/done automatically.
I know this is not very convenient, but currently the alternative to doing it manually when simply copying the project file.
In v4 the projects will have a completely different structure and functionality that is suitable for source control and will allow you to simply synchronize the project data itself without having to adjust anything.
The reason why the paths etc. are hardcoded relies on a very early version of nUpdate (Administration) and due to time pressure I did not really improve it before the official release became public.
Sorry for that, but thanks for expressing your improvement proposal. I understand the problem and have already thought deeply about fixing it. The solution will be a project management that is based on the one of Visual Studio.

Best,
Dominic
