### ISSUE TITLE
Connecting via FTP

### ISSUE THREAD

**Issue by snrchang** [ProgTrade/nUpdate#47]
I always get the error

Field must contain equals "-" value with only a name and value

**Comment by ProgTrade** [comment]
Hi,

unfortunately, I can't directly say what the problem may refer to due to the fact that you did not give any further information. Where does the error appear? And could you copy the complete StackTrace (right-click on the error text and select "Copy entire message")?

Best,
Dominic

**Comment by Cjay93** [comment]
Thanks i fixed it, weird error on sever side.
Another problem though is that it gives a error on installing update the the .exe is in use.
Could you give a example of using nupdate please.
this is my code that give error on update the program .exe

`  Try
            Dim manager As New UpdateManager(New Uri("https://?/Update/updates.json"), "<RSAKeyValue><Modulu></Modulus><Exponent>AQAB</Exponent></RSAKeyValue>", New CultureInfo("en"))
            manager.SearchForUpdates()
            Dim updaterUIc As New UpdaterUI(manager, SynchronizationContext.Current)
            updaterUIc.UseHiddenSearch = True
            updaterUIc.ShowUserInterface()


        Catch ex As Exception
            MsgBox(ex.Message & ex.Source)
        End Try`
I removed the Url and RSA key for example.

**Comment by ProgTrade** [comment]
Hello,

your call of `SearchForUpdates` is redundant. All the steps needed for updating are automatically done in the `UpdaterUI` class when calling `ShowUserInterface`. This searches the updates, shows the available ones, downloads them and installs them.
So, you can just remove this line.

I do not think that your problem is associated with your code. It should then be fine. Are you using WPF or a console application? It may be that the application shutdown may not work correctly due to specific application behaviour.

Best,
Dominic

**Comment by Cjay93** [comment]
Thanks
